{
 "title": "cPanel UAPI exporter",
 "description": "Grafana dashboard for cPanel exporter:\r\nhttps://github.com/nimaam/cpanel_exporter\r\n\r\nThe dashboard is designed compatible with both the admin and individual cPanel accounts.\r\n\r\nAuthor: https://github.com/nimaam\r\n",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Account Information",
   "type": "table",
   "description": "Go to Value options > Fields and choose the field to fix the panel",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "cpanel_info{}",
     "legendFormat": "OS: {{operatingsystem}} {{machinetype}} | cPanel version: {{cpanelversion}} | cPanel user: {{user}} | Package: {{hostingpackage}} | Hostname: {{hostname}} | Short hostname: {{shorthostname}} | IP: {{ip}} | Kernel version: {{kernelversion}} | Perl version: {{perlversion}} | MySQL version: {{mysqlversion}}"
    }
   ]
  },
  {
   "title": "High priority resources | Used",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "timeseries",
     "description": "CPU Usage specifies how much of the allocated CPU resources you are currently using. The amount of CPU resources we provide to each account is the percentage of the server’s resources.\nIf CPU reaches 100% it means that your account is using all of the CPU resources allocated, and any new processes will be put to sleep until existing processes complete. This can cause your website to slow down dramatically and in extreme cases even time out.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "cpanel_cpu{}", "legendFormat": "{{user}} ({{shorthostname}})" }
     ]
    },
    {
     "title": "CPU usage | Percent",
     "type": "timeseries",
     "description": "CPU Usage specifies how much of the allocated CPU resources you are currently using. The amount of CPU resources we provide to each account is the percentage of the server’s resources.\nIf CPU reaches 100% it means that your account is using all of the CPU resources allocated, and any new processes will be put to sleep until existing processes complete. This can cause your website to slow down dramatically and in extreme cases even time out.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expr": "cpanel_cpu_percent{}", "legendFormat": "{{user}} ({{shorthostname}})" }
     ]
    },
    {
     "title": "Memory usage",
     "type": "timeseries",
     "description": "Physical Memory Usage (RAM) is the actual memory allocated for your account. Virtual memory is usually a file on a disk drive that the operating system uses to store information (swap-to-from) when the real memory becomes full, for instance, the page (swap) file on a Linux system. Therefore, if you try to publish a big post, it might take all physical memory to do so, but after some time it will be normalized.\n\nIf this value reaches the limit you may begin to experience PHP errors (if applicable) on your website, or in very extreme cases may see a CloudLinux error page. These errors are typically only brief and once the usage has reduced to below the limit, will automatically clear.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "cpanel_memphy{}", "legendFormat": "{{user}} ({{shorthostname}})" }
     ]
    },
    {
     "title": "Memory usage | Percent",
     "type": "timeseries",
     "description": "Physical Memory Usage (RAM) is the actual memory allocated for your account. Virtual memory is usually a file on a disk drive that the operating system uses to store information (swap-to-from) when the real memory becomes full, for instance, the page (swap) file on a Linux system. Therefore, if you try to publish a big post, it might take all physical memory to do so, but after some time it will be normalized.\n\nIf this value reaches the limit you may begin to experience PHP errors (if applicable) on your website, or in very extreme cases may see a CloudLinux error page. These errors are typically only brief and once the usage has reduced to below the limit, will automatically clear.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expr": "cpanel_memphy_percent{}", "legendFormat": "{{user}} ({{shorthostname}})" }
     ]
    },
    {
     "title": "Disk space",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "cpanel_diskusage{}", "legendFormat": "{{user}} ({{shorthostname}})" }
     ]
    },
    {
     "title": "Disk space | Percent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expr": "cpanel_diskusage_percent{}", "legendFormat": "{{user}} ({{shorthostname}})" }
     ]
    },
    {
     "title": "Files usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "cpanel_filesusage{}", "legendFormat": "{{user}} ({{shorthostname}})" }
     ]
    },
    {
     "title": "Files usage | Percent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expr": "cpanel_filesusage_percent{}", "legendFormat": "{{user}} ({{shorthostname}})" }
     ]
    }
   ]
  },
  {
   "title": "High priority resources | Free",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Free disk space",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "cpanel_free_diskusage{}", "legendFormat": "{{user}} ({{shorthostname}})" }
     ]
    },
    {
     "title": "Free disk space | Percent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "cpanel_free_diskusage_percent{}",
       "legendFormat": "{{user}} ({{shorthostname}})"
      }
     ]
    },
    {
     "title": "Free files usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "cpanel_free_filesusage{}", "legendFormat": "{{user}} ({{shorthostname}})" }
     ]
    },
    {
     "title": "Free files usage | Percent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "cpanel_free_filesusage_percent{}",
       "legendFormat": "{{user}} ({{shorthostname}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Databases",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL version",
     "type": "stat",
     "description": "Go to Value options > Fields and choose the field to fix the panel",
     "gridPos": { "h": 3, "w": 12, "x": 6, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "cpanel_info{}", "legendFormat": "{{mysqlversion}}" }
     ]
    },
    {
     "title": "MySQL disk space used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "cpanel_mysqldiskusage{}", "legendFormat": "{{user}} ({{shorthostname}})" }
     ]
    },
    {
     "title": "MySQL databases count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "cpanel_mysqldatabases{}", "legendFormat": "{{user}} ({{shorthostname}})" }
     ]
    },
    {
     "title": "Individual MySQL dbs disk usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "cpanel_mysql_db_disk_usage{}",
       "legendFormat": "{{db}} ({{user}}) {{shorthostname}}"
      }
     ]
    },
    {
     "title": "Cached MySQL disk used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "cpanel_cachedmysqldiskusage{}", "legendFormat": "{{user}} ({{shorthostname}})" }
     ]
    },
    {
     "title": "PostGreSQL databases count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 7, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "cpanel_postgresqldatabases{}", "legendFormat": "{{user}} ({{shorthostname}})" }
     ]
    },
    {
     "title": "PostGreSQL disk used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "cpanel_postgresqldiskusage{}", "legendFormat": "{{user}} ({{shorthostname}})" }
     ]
    },
    {
     "title": "Individual PostGreSQL dbs disk usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "cpanel_postgres_db_disk_usage{}",
       "legendFormat": "{{db}} ({{user}}) {{shorthostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Low priority resources | Used",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "I/O usage",
     "type": "timeseries",
     "description": "I/O Usage (input/output) represents how much I/O (or disk activity) your account is using. Any task which makes use of the servers disk drive (such as reading or writing to the server) will consume I/O. We limit the maximum disk speed of each account to ensure that no single account can saturate the disk drives which will reduce performance for everyone.\nReaching this limit will cause all processes to slow down (to within this limit) and take much longer to complete. Typically you won’t notice this setting ever increase unless you perform something disk intensive like generating a large backup of your account.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      { "expr": "cpanel_io{}", "legendFormat": "{{user}} ({{shorthostname}})" }
     ]
    },
    {
     "title": "IOPS",
     "type": "timeseries",
     "description": "IOPS, or Input/Output Operations Per Second, is a performance metric used to measure the speed of input/output operations on a storage device. It represents the number of read and write operations that a storage system can perform in one second. Higher IOPS values indicate better performance and faster data access.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "cpanel_iops{}", "legendFormat": "{{user}} ({{shorthostname}})" }
     ]
    },
    {
     "title": "Entry Processes",
     "type": "timeseries",
     "description": "Entry Processes is the number of processes that enter your account. It is also known as \"Apache concurrent connections\". This value defines how many PHP or CGI scripts you can run at a single time. For example, every PHP page that is accessed by a user will usually generate a single entry process. Many people misinterpret this value as “number of visitors you can have on your website at once”. Whilst it is true that each visitor accessing a PHP page will spawn an entry process, these processes usually end so quickly that it is extremely unlikely that 10 will be spawned concurrently and at a single moment unless you had a significantly large number of simultaneous visitors on your website at once.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "cpanel_ep{}", "legendFormat": "{{user}} ({{shorthostname}})" }
     ]
    },
    {
     "title": "Processes count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "cpanel_nproc{}", "legendFormat": "{{user}} ({{shorthostname}})" }
     ]
    },
    {
     "title": "Monthly Bandwidth usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "cpanel_bandwidthusage{}", "legendFormat": "{{user}} ({{shorthostname}})" }
     ]
    }
   ]
  },
  {
   "title": "Emails",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Email account disk space used",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "cpanel_email_disk_usage{}",
       "legendFormat": "{{email}} ({{user}}) {{shorthostname}}"
      }
     ]
    },
    {
     "title": "Email accounts count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "cpanel_emailaccounts{}", "legendFormat": "{{user}} ({{shorthostname}})" }
     ]
    },
    {
     "title": "Email filters count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "cpanel_emailfilters{}", "legendFormat": "{{user}} ({{shorthostname}})" }
     ]
    },
    {
     "title": "Email forwarders count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "cpanel_emailforwarders{}", "legendFormat": "{{user}} ({{shorthostname}})" }
     ]
    },
    {
     "title": "Cached email accounts disk space used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "cpanel_cachedlistdiskusage{}", "legendFormat": "{{user}} ({{shorthostname}})" }
     ]
    }
   ]
  },
  {
   "title": "Other",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Addon domains count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "cpanel_addondomains{}", "legendFormat": "{{user}} ({{shorthostname}})" }
     ]
    },
    {
     "title": "Subdomains count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "cpanel_subdomains{}", "legendFormat": "{{user}} ({{shorthostname}})" }
     ]
    },
    {
     "title": "FTP account disk space used",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "cpanel_ftp_account_disk_usage{}",
       "legendFormat": "{{ftp_account}} ({{user}}) {{shorthostname}}"
      }
     ]
    },
    {
     "title": "Parked domains count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "cpanel_parkeddomains{}", "legendFormat": "{{user}} ({{shorthostname}})" }
     ]
    }
   ]
  }
 ]
}